name: Hayatta Mesajı

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  hayatta-mesaji:
    runs-on: ubuntu-latest
    steps:
      - name: Mesaj At
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="👀 Hâlâ nöbetteyim aga, L beden stoka girmedi."